import { readFileSync, statSync } from "node:fs"
import { describe, expect, it } from "vitest"

const read = (path: string) => readFileSync(path, "utf8")

describe("Skill Overview", () => {
  it("leads with an accessible RVI profile and preserves both evidence inspectors", () => {
    const overview = read("src/components/skill/SkillOverview.vue")
    const profile = read("src/components/skill/PerformanceProfile.vue")
    const metricList = read("src/components/skill/RviMetricList.vue")
    const rviContexts = read("src/helpers/rvi-contexts.ts")
    const engine = read("electron/main/matches/performance-profile.ts")
    const vocabulary = read("src/shared/performance-vocabulary.ts")

    expect(overview).toMatch(/PerformanceProfile[\s\S]*TelemetryBoard[\s\S]*RankedHistoryPanel[\s\S]*title="Recorded comparisons"/)
    expect(overview).toContain("classifyRviIdentity")
    expect(overview).toContain("overview.performance")
    expect(overview).not.toContain("classifyPlaystyle")
    expect(overview).not.toContain('title="Playstyle"')
    expect(profile).toContain("RVI profile")
    expect(profile).toContain("identity?.label")
    expect(profile).toContain("identity?.description")
    expect(profile).toContain('class="rvi-profile-header"')
    expect(profile).toContain('class="rvi-overall" aria-label="Career RVI summary"')
    expect(profile).toContain("Career RVI ${profile.score} out of 100")
    expect(profile).toContain('class="rvi-stage"')
    expect(profile).toMatch(/Profile shape[\s\S]*PerformanceRadar[\s\S]*class="rvi-highlights"/)
    expect(profile).toContain('class="rvi-highlights" aria-label="RVI profile highlights"')
    expect(profile).toContain("Strongest arm")
    expect(profile).toContain("Largest recent gain")
    expect(profile).toContain("No clear recent gain")
    expect(profile).toContain("profile.comparison")
    expect(profile).toContain("strongest.label")
    expect(profile).toContain("growth.label")
    expect(profile).toContain("RVI by context")
    expect(profile).toContain('<h3 id="rvi-context-title">RVI by context</h3>')
    expect(profile).toContain('aria-describedby="rvi-context-description"')
    expect(profile).toContain(':aria-labelledby="`rvi-context-best-${group.key}`"')
    expect(profile).toContain('<ul role="list">')
    expect(profile).toContain("performanceScopeAriaLabel(scope)")
    expect(rviContexts).toContain("${performanceScopeLabel(scope)} ${context} RVI, ${scope.score} out of 100")
    expect(profile).toContain("hasScopeComparisons")
    expect(profile).toContain("contextGroups")
    expect(profile).toContain("bestContextGroups")
    expect(profile).toContain("items: group.items.slice(0, 1)")
    expect(profile).toContain("rankPerformanceScopes")
    expect(profile).not.toContain("remainingContextGroups")
    expect(profile).not.toContain("rvi-context-more")
    expect(profile).toContain("gameCountLabel")
    expect(rviContexts).toContain(" of ${scope.headline.totalArms} arms")
    expect(profile).not.toContain("--scope-count")
    expect(profile).not.toContain('class="scope-card"')
    expect(profile).not.toContain('class="story-card')
    const contextBlock = profile.slice(
      profile.indexOf('v-if="hasScopeComparisons"'),
      profile.indexOf('<section class="rvi-stage"'),
    )
    expect(contextBlock).not.toContain("<button")
    expect(contextBlock).not.toContain("@click")
    expect(contextBlock).not.toContain("tabindex")
    expect(profile).toMatch(/class="rvi-context"[\s\S]*class="rvi-stage"[\s\S]*class="rvi-arms"/)
    expect(profile).toContain('<h3 id="rvi-arms-title">Performance arms</h3>')
    expect(profile).toContain('class="career-arm-grid" role="group" aria-labelledby="rvi-arms-title"')
    expect(profile).toContain('class="career-arm"')
    expect(profile).toContain('class="career-arm-result"')
    expect(profile).toContain('class="career-arm-trend"')
    expect(profile).toContain('@click="selectDimension(dimension.key)"')
    expect(profile).toContain(':aria-pressed="selected?.key === dimension.key"')
    expect(profile).toContain('aria-controls="career-arm-details"')
    expect(profile).toContain("if (props.detailOnly) detailsOpen.value = true")
    expect(profile).toContain("career-inspector")
    expect(profile).toContain("career-inspector-toggle")
    expect(profile).toContain(':aria-expanded="careerDetailsOpen"')
    expect(profile).toContain('v-show="careerDetailsOpen"')
    expect(profile).toContain("careerDetailsOpen ? 'Hide details' : 'Show details'")
    expect(profile).toContain("Used in score")
    expect(profile).toContain("More signals")
    expect(profile).toContain("Unavailable")
    expect(profile).toContain("RviMetricList")
    expect(profile).toContain("@container rvi-profile")
    expect(profile).toContain("grid-template-columns: repeat(4, minmax(0, 1fr))")
    expect(profile).toContain("grid-auto-rows: 1fr")
    expect(profile).not.toContain("Recorded RVI scopes")
    expect(profile).toContain("How scoring works")
    expect(profile).toContain("measurement-table")
    expect(profile).toContain("segment-meter")
    expect(profile).toContain(':aria-expanded="detailsOpen"')
    expect(profile).toContain(':aria-controls="`dimension-${selected.key}`"')
    expect(profile).toContain('v-if="detailsOpen"')
    expect(profile).toContain('class="detail-only-head"')
    expect(profile).toContain("Influence")
    expect(profile).toContain("metric.games")
    expect(profile).toContain("dimension-grid")
    expect(profile).toContain("Select an arm to see the measurements behind this match")
    expect(profile).not.toContain("measured in {{ profile.dimensions.length }} vectors")
    expect(profile).not.toContain("RVI keeps eight stable capability views")
    expect(profile).toContain("Missing optional stats never count as zero")
    expect(profile).not.toContain("metric.evidenceReason")
    expect(metricList).not.toContain("metric.evidenceReason")
    expect(profile).toContain("metric.vectorWeight")
    expect(profile).toContain("metric.gradeInfluence")
    expect(metricList).toContain("metric.vectorWeight")
    expect(metricList).toContain("metric.gradeInfluence")
    expect(metricList).toContain("metric.rawValue")
    expect(metricList).toContain("metric.coverage")
    expect(metricList).toContain("metric.comparison")
    expect(metricList).toContain("metric.referenceMatchCount")
    expect(metricList).toContain("metric.formula")
    expect(metricList).toContain('<details v-for="metric in metrics"')
    expect(profile).toContain("Primary archetype")
    expect(profile).not.toContain("primaryArchetypes.slice(0, 2)")
    expect(profile).not.toContain("Champion + position")
    expect(profile).not.toContain("championPositions")
    expect(rviContexts).toContain("scope.measuredGames")
    expect(rviContexts).toContain("headline.availableArms")
    expect(profile).toContain("Shown for detail only")
    expect(profile).toContain("responsibilityWeight")
    expect(profile).toContain("Core measurements")
    expect(profile).toContain("Secondary measurements")
    expect(profile).toContain("Unavailable or not applicable")
    expect(profile).toContain("metricRawLabel")
    expect(profile).toContain("metric.formula")
    expect(overview).not.toMatch(/<PerformanceProfile[\s\S]*?:champions="champions"/)
    expect(profile).not.toContain("remaining weights rebalance")
    expect(engine).toContain("RVI_VECTOR_DEFINITIONS")
    expect(vocabulary).toContain('label: "Macro"')
    expect(vocabulary).toContain("Staying alive and avoiding costly deaths")
  })

  it("offers queue and season-selectable ranked growth history", () => {
    const overview = read("src/components/skill/SkillOverview.vue")
    const ranked = read("src/components/RankedHistoryPanel.vue")

    expect(overview).toContain("RankedHistoryPanel")
    expect(overview).toContain("allow-season-selection")
    expect(overview).toMatch(/PerformanceProfile[\s\S]*RankedHistoryPanel[\s\S]*compact/)
    expect(ranked).toContain("All seasons")
    expect(ranked).toContain('v-model="selectedQueue"')
    expect(ranked).toContain('v-model="selectedSeason"')
    expect(ranked).toContain("change")
  })

  it("uses literal Recall and an RVI-native identity", () => {
    const overview = read("src/components/skill/SkillOverview.vue")

    expect(overview).toContain("Average Recall Score")
    expect(overview).toContain("TelemetryBoard")
    expect(overview).toContain("graded")
    expect(overview).toContain("rviIdentity")
    expect(overview).not.toMatch(/strengths|weaknesses|you play best|to work on/i)
  })

  it("keeps interpretation-only rates out of Overview", () => {
    const overview = read("src/components/skill/SkillOverview.vue")

    expect(overview).not.toContain("coreWinRate")
    expect(overview).not.toContain("restWinRate")
    expect(overview).not.toMatch(/item.*winRate/i)
  })

  it("labels lobby comparison scope and custom grade coverage", () => {
    const overview = read("src/components/skill/SkillOverview.vue")

    expect(overview).toContain("metric.scope")
    expect(overview).toContain("Recall grade")
    expect(overview).toContain("gradedGames")
  })

  it("uses one RVI performance profile", () => {
    const overview = read("src/components/skill/SkillOverview.vue")

    expect(overview).toContain("<PerformanceProfile")
    expect(overview).toContain(':identity="rviIdentity"')
  })

  it("keeps the useful scoped outcome visuals", () => {
    const overview = read("src/components/skill/SkillOverview.vue")

    expect(overview).toContain("OutcomeTrendChart")
    expect(overview).toContain("Game length")
    expect(overview).toContain("Time of day")
  })
})

describe("Skill Insights", () => {
  it("renders one consolidated story in order without duplicate champion and outcome panels", () => {
    const insights = read("src/components/skill/SkillInsights.vue")
    const contexts = read("src/components/skill/RviContextBreakdown.vue")

    expect(insights).toMatch(
      /RviContextBreakdown[\s\S]*Performance over time[\s\S]*Grade drivers[\s\S]*SkillContextExplorer[\s\S]*Evidence/,
    )
    expect(contexts).toContain('<p class="chapter">RVI context</p>')
    expect(contexts).toContain("Where your RVI is strongest")
    expect(contexts).toContain("rankPerformanceScopes")
    expect(contexts).toContain("FEATURED_ARCHETYPE_COUNT = 4")
    expect(contexts).toContain('<details v-if="remainingArchetypes.length"')
    expect(contexts).toContain("Show {{ remainingArchetypes.length }} more archetypes")
    expect(contexts).toContain("Hide additional archetypes")
    expect(contexts).toContain("@container rvi-context-insights (max-width: 360px)")
    expect(contexts).toContain('<ol class="scope-grid position-grid">')
    expect(contexts).not.toContain("<button")
    expect(insights).toContain("GradeJourneyChart")
    expect(insights).toContain("GradeDnaHeatmap")
    expect(insights).toContain("EvidenceForestPlot")
    expect(insights).not.toContain("OutcomeTrendChart")
  })

  it("orders Grade Journey chronologically and compares two honest ten-match windows", () => {
    const insights = read("src/components/skill/SkillInsights.vue")
    const journey = read("src/components/skill/GradeJourneyChart.vue")

    expect(insights).toContain(".sort((left, right) => left.playedAt - right.playedAt)")
    expect(insights).toContain("allValues.length < 20")
    expect(insights).toContain("values.slice(0, 10)")
    expect(insights).toContain("values.slice(10)")
    expect(journey).toContain('type: "scatter"')
    expect(journey).toContain("rollingWindow")
    expect(journey).toContain('game.win ? "circle" : "diamond"')
    expect(journey).toContain("Match result symbols")
    expect(insights).toContain("No graded matches are available")
  })

  it("shows Grade drivers with truthful score, share, and plain-language influence labels", () => {
    const insights = read("src/components/skill/SkillInsights.vue")
    const heatmap = read("src/components/skill/GradeDnaHeatmap.vue")

    expect(insights).toContain("component.contribution * 100")
    expect(insights).toContain("component.weight * 100")
    expect(insights).toContain("points in the mix")
    expect(heatmap).toContain("Influence on the Grade mix")
    expect(heatmap).toContain("Grade share")
    expect(heatmap).toContain("Arm score")
    expect(heatmap).toContain('`#${index + 1}`')
    expect(heatmap).toContain("championNameById(props.champions")
  })

  it("presents a summary-first pattern queue while preserving every evidence range", () => {
    const insights = read("src/components/skill/SkillInsights.vue")
    const forest = read("src/components/skill/EvidenceForestPlot.vue")

    expect(insights).toContain("evidenceGroups")
    expect(insights).toContain("props.report.insights.champions")
    expect(insights).toContain("section.findings.filter((finding) => Number.isFinite(finding.effect))")
    expect(forest).toContain("Worth reviewing")
    expect(forest).toContain("Still learning")
    expect(forest).toContain("Compare every measured estimate")
    expect(forest).toContain("findingSummary")
    expect(forest).toContain("item.finding.scope")
    expect(forest).toContain("item.finding.caveat")
    expect(forest).toContain("hasUsableInterval")
  })

  it("only promotes a ready predictive model and labels its target correctly", () => {
    const insights = read("src/components/skill/SkillInsights.vue")
    const effectChart = read("src/components/skill/EffectChart.vue")

    expect(insights).toContain('state === "ready"')
    expect(insights).toContain("top-quarter Recall Score")
    expect(insights).toContain("not a win")
    expect(insights).toContain("report.insights.predictive.message")
    expect(effectChart).toContain("top-quartile Recall Score probability effects")
    expect(effectChart).toContain('type: "bar"')
  })

  it("keeps day, time, and duration in one collapsed, keyboard-safe context explorer", () => {
    const explorer = read("src/components/skill/SkillContextExplorer.vue")
    const weekday = read("src/components/skill/WeekdayGradeBoxplot.vue")
    const duration = read("src/components/skill/DurationGradeScatter.vue")

    expect(explorer).toContain('<details class="context-explorer"')
    expect(explorer).toContain('role="group"')
    expect(explorer).toContain(':aria-pressed="view === item.key"')
    expect(explorer).toContain("WeekdayGradeBoxplot")
    expect(explorer).toContain("OutcomeTrendChart")
    expect(explorer).toContain("DurationGradeScatter")
    expect(explorer).toContain(':champions="champions"')
    expect(explorer).not.toContain('role="tab"')
    expect(explorer).not.toContain('role="tabpanel"')
    expect(weekday).toContain("group.eligible")
    expect(weekday).toContain('v-if="eligibleGroups.length"')
    expect(weekday).toContain("At least 3 graded matches")
    expect(weekday).toContain("Still learning")
    expect(duration).toContain("durationRecallScoreBins")
    expect(duration).toContain("MIN_DURATION_TREND_GAMES")
    expect(duration).toContain('smooth: false')
    expect(duration).toContain('connectNulls: false')
    expect(duration).toContain('game.win ? "circle" : "diamond"')
    expect(duration).toContain("championNameById(props.champions")
    expect(duration).toContain("5-minute median · 5+ matches")
  })

  it("uses ECharts everywhere and leaves reduced motion to the shared wrapper", () => {
    const wrapper = read("src/components/charts/BaseEChart.vue")
    const packageJson = read("package.json")

    expect(wrapper).toContain("prefers-reduced-motion")
    expect(wrapper).toContain("ResizeObserver")
    expect(packageJson).toContain('"echarts": "6.1.0"')
    expect(packageJson).not.toContain('"chart.js"')
    expect(packageJson).not.toContain('"vue-chartjs"')
  })

  it("keeps generated report copy associative", () => {
    const reportSource = read("electron/main/matches/skill-report.ts").toLowerCase()

    for (const forbidden of [" causes ", " makes you ", " optimal ", " true skill "]) {
      expect(reportSource).not.toContain(forbidden)
    }
  })
})

describe("Skill page coordination", () => {
  it("defaults to current-season Ranked Solo and restores saved filters", () => {
    const page = read("src/pages/SkillPage.vue")

    expect(page).toContain('ref<SkillScopeId>("rankedSolo")')
    expect(page).toContain("currentRankedSeason()")
    expect(page).toContain("api.getSkillViewPreferences()")
    expect(page).toContain("api.saveSkillViewPreferences(currentPreferences())")
    expect(page).toContain("rviArmDetailsOpen")
    expect(page).toContain("preferences.rviArmDetailsOpen ?? true")
    expect(page).toContain('@update:rvi-arm-details-open="setRviArmDetailsOpen"')
    expect(page).toContain("rankedSeasonById(seasonId.value)")
    expect(page).not.toContain("choseInitialScope")
  })

  it("keeps tabs local and uses one report fetch path", () => {
    const page = read("src/pages/SkillPage.vue")

    expect(page).toContain("import type { SkillTab, SkillViewPreferences }")
    expect(page).toContain('ref<SkillTab>("overview")')
    expect(page).toContain("<SkillInsights")
    expect(page).toContain("<SkillAnalyze")
    expect(page).toContain("Analyze")
    expect(page).toMatch(/Overview[\s\S]*Insights[\s\S]*Analyze/)
    expect(page.match(/getSkillReport/g)).toHaveLength(1)
    expect(page).not.toMatch(/@click="[^\"]*loadReport[^\"]*"[^>]*>\s*Insights/)
  })

  it("uses compact selects and a searchable visual champion picker", () => {
    const page = read("src/pages/SkillPage.vue")
    const championPicker = read("src/components/ChampionPicker.vue")

    expect(page).toContain("riftScopes")
    expect(page).toContain("abyssScopes")
    expect(page).toContain("classicScopes")
    expect(page).toContain("counts[scope.id]")
    expect(page).toContain('v-model="seasonId"')
    expect(page).toContain('v-model="role"')
    expect(page).toContain('v-model="championId"')
    expect(page).toContain("ChampionPicker")
    expect(page).toContain('class="league-select"')
    expect(page).not.toContain('class="scope-button')
    expect(championPicker).toContain('type="search"')
    expect(championPicker).toContain('class="champion-grid"')
    expect(championPicker).toContain("championIconUrl")
    expect(championPicker).toContain('role="listbox"')
  })

  it("maps persisted death density over an optimized Rift image", () => {
    const overview = read("src/components/skill/SkillOverview.vue")
    const analyze = read("src/components/skill/SkillAnalyze.vue")
    const heatmap = read("src/components/skill/DeathHeatmap.vue")
    const mapAsset = statSync("public/summoners-rift-base.webp")

    expect(overview).not.toContain("DeathHeatmap")
    expect(analyze).toContain("DeathHeatmap")
    expect(analyze).toContain("report.overview.deathMap")
    expect(analyze).toContain("report.scope.family === 'sr'")
    expect(heatmap).toContain('type: "heatmap"')
    expect(heatmap).toContain('type: "scatter"')
    expect(heatmap).toContain('type: "category"')
    expect(heatmap).toContain("xAxisIndex: 1")
    expect(heatmap).toContain("yAxisIndex: 1")
    expect(heatmap).toContain("Array.isArray(item.data)")
    expect(heatmap).toContain("nearbyDeaths")
    expect(heatmap).toContain("nearby death")
    expect(heatmap).toContain("% of deaths in this selection")
    expect(heatmap).toContain("Average death")
    expect(heatmap).not.toContain("relative density")
    expect(heatmap).toContain("summoners-rift-base.webp")
    expect(heatmap).toMatch(/mode,\s*season, position, and champion filters above/)
    expect(heatmap).toContain("before 15 min")
    expect(heatmap).toContain("15–30 min")
    expect(heatmap).toContain("Heat overlay")
    expect(heatmap).toContain("Death dots")
    expect(heatmap).toContain("visualization")
    expect(heatmap).not.toContain("Rank hotspots")
    expect(heatmap).toContain("rankedHotspots")
    expect(heatmap).toContain("cell.density / Math.max(1, props.map.timelineGames)")
    expect(heatmap).toContain("how many games have timeline data")
    expect(heatmap).toContain("HEAT_DENSITY_SCALE_MAX")
    expect(heatmap).toContain("HEAT_STOPS")
    expect(heatmap).toContain('class="map-layout"')
    expect(heatmap).toContain('class="hotspot-aside"')
    expect(mapAsset.size).toBeLessThan(1_000_000)
  })

  it("builds Analyze from honest RVI and Recall Grade views", () => {
    const analyze = read("src/components/skill/SkillAnalyze.vue")
    const signatures = read("src/components/skill/MatchSignaturesChart.vue")
    const form = read("src/components/skill/PerformanceFormChart.vue")
    const champions = read("src/components/skill/ChampionQuadrantChart.vue")

    expect(analyze).toContain("PerformanceFormChart")
    expect(analyze).toContain("MatchSignaturesChart")
    expect(analyze).toContain("SessionEnduranceChart")
    expect(analyze).toContain("ChampionQuadrantChart")
    expect(analyze).toContain("ChampionLearningCurve")
    expect(analyze).toContain("armFormComparisons")
    expect(analyze).toContain("Two separate measured windows")
    expect(analyze).toContain("Match Grade inspector")
    expect(signatures).toContain("Result unavailable")
    expect(signatures).toContain("points in the mix")
    expect(signatures).not.toContain('type: "parallel"')
    expect(form).toContain("armFormComparisons")
    expect(form).toContain("Career-only Range is excluded")
    expect(form).toContain('import { CHART_COLOURS, CHART_STYLES } from "../../charts/recall-chart-theme"')
    expect(form).toContain("color: CHART_COLOURS.text")
    expect(form).toContain("textBorderWidth: 0")
    expect(analyze).toMatch(/Each champion\s+portrait marks that champion's result/)
    expect(champions).toContain('symbol: `image://${championIconUrl(champion.championId)}`')
    expect(champions).toContain("symbolSize: 30")
    expect(champions).toContain('class="accessible-summary"')
    expect(analyze).toContain("align-items: stretch")
    expect(analyze).toContain("height: 100%")
  })
})
